In [1]:
import pandas as pd

In [2]:
olympics_complete=pd.read_csv('../intermediate/olimpics_gdp_population.csv')
base_data_male = olympics_complete.loc[olympics_complete['Sex'] == "M",
                                              ['Sport',
                                               'Age',
                                               'Weight',
                                               'Height',
                                               'Medal_Won',
                                               'Event_Category',
                                               'GDP',
                                               'Population',
                                               'Team']].drop_duplicates()

In [3]:
olympics_complete.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'NOC', 'Games', 'Year',
       'Season', 'City', 'Sport', 'Event', 'Medal', 'Team', 'Country Code',
       'GDP', 'Population', 'Medal_Won', 'Team_Event', 'Single_Event',
       'Event_Category', 'Country_Host'],
      dtype='object')

In [4]:
no_medal_mask=base_data_male['Medal_Won']==0
medal_mask = [not i for i in no_medal_mask]

In [5]:
medal_winner=base_data_male[medal_mask].copy()
medal_winner['Medal_Won_Corrected'] = medal_winner['Medal_Won']/medal_winner['Event_Category']

In [6]:
medal_winner=base_data_male[medal_mask][['Age','Sport','Weight','Height','GDP','Population']]

In [7]:
medal_winner_grouped=medal_winner.groupby(by=['Sport']).mean()
medal_winner_grouped['Won']=1
medal_winner_grouped

,Age,Weight,Height,GDP,Population,Won
Sport,,,,,,
Archery,25.306122,78.588542,178.989583,1.565370e+12,1.617803e+08,1
Athletics,25.430626,78.739848,182.760980,6.005976e+11,5.831168e+07,1
Badminton,26.313253,72.925000,178.843373,2.068256e+12,5.488797e+08,1
Baseball,26.271642,85.804217,182.436747,1.544831e+12,4.896194e+07,1
Basketball,25.504032,96.781377,199.468687,5.803172e+11,3.260007e+07,1
Beach Volleyball,29.944444,90.878788,194.000000,1.373445e+12,1.054623e+08,1
Boxing,23.335484,67.636289,174.829787,4.793510e+11,5.603511e+07,1
Canoeing,25.719328,82.595798,182.951261,9.394380e+11,4.724860e+07,1
Cycling,24.729927,76.012868,180.533088,8.221504e+11,3.986568e+07,1
Diving,22.877049,65.450820,171.049180,2.553295e+12,6.630956e+08,1
Equestrianism,36.233618,72.223496,178.389685,9.106826e+11,5.122221e+07,1
Fencing,27.210801,77.047619,181.982363,1.060448e+12,7.378190e+07,1
Football,23.509915,74.107195,178.359534,7.572599e+11,7.458450e+07,1
Golf,38.000000,86.000000,190.666667,5.144600e+11,9.903122e+06,1
Gymnastics,23.385757,61.331818,165.831325,1.883586e+12,2.970735e+08,1
Handball,27.413002,91.592593,190.378168,1.107667e+12,3.425907e+07,1
Hockey,25.666161,75.223602,178.327640,7.906768e+11,9.833697e+07,1
Judo,25.271676,86.566766,178.100890,1.328505e+12,6.729851e+07,1
Modern Pentathlon,27.406250,73.205263,180.694737,5.308635e+11,4.639204e+07,1
Rowing,26.317136,86.603790,189.072227,7.858216e+11,3.834335e+07,1
Rugby Sevens,25.842105,92.368421,183.368421,1.500799e+11,2.840381e+07,1
Sailing,30.541152,80.991736,181.752066,5.670502e+11,4.070919e+07,1
Shooting,30.943787,79.128358,177.059524,1.049607e+12,2.112285e+08,1
Swimming,22.089974,81.357237,187.641732,1.308307e+12,8.125770e+07,1
Table Tennis,25.434783,69.058824,176.058824,3.025431e+12,7.281307e+08,1
Taekwondo,24.027778,75.972222,185.333333,1.231125e+12,1.438984e+08,1
Tennis,26.565789,80.750000,186.486842,9.651566e+11,5.201301e+07,1
Trampolining,23.733333,65.600000,171.800000,4.529517e+12,6.942228e+08,1
Triathlon,27.000000,69.800000,181.066667,9.474658e+11,3.282714e+07,1
Volleyball,26.802444,88.239175,193.979424,7.843340e+11,7.379870e+07,1
Water Polo,26.321429,91.488844,189.995943,4.750232e+11,2.358141e+07,1
Weightlifting,25.161644,84.337900,169.022727,9.188647e+11,2.146800e+08,1
Wrestling,25.821900,78.287798,173.550398,5.469850e+11,5.218905e+07,1

In [8]:
no_medal_winner=base_data_male[no_medal_mask][['Age','Sport','Weight','Height','GDP','Population']]

In [9]:
no_medal_winner_grouped=no_medal_winner.groupby(by='Sport').mean()
no_medal_winner_grouped['Won']=0
no_medal_winner_grouped

,Age,Weight,Height,GDP,Population,Won
Sport,,,,,,
Archery,27.469014,76.708006,178.261654,7.817921e+11,1.355641e+08,0
Athletics,25.798005,74.596449,180.394560,5.048194e+11,5.898869e+07,0
Badminton,26.412727,74.313544,179.589744,1.121539e+12,2.185128e+08,0
Baseball,26.292910,85.650000,182.683694,1.386614e+12,1.081603e+08,0
Basketball,25.791847,91.915829,195.895485,6.102274e+11,1.333987e+08,0
Beach Volleyball,29.888889,89.325000,193.194215,1.034398e+12,6.510628e+07,0
Boxing,23.289082,64.805023,172.678687,3.305664e+11,5.921771e+07,0
Canoeing,25.382251,79.423002,181.064729,6.384873e+11,6.682563e+07,0
Cycling,24.906871,71.874201,177.945583,5.670911e+11,4.961415e+07,0
Diving,22.742029,67.178906,171.661466,7.757653e+11,9.287189e+07,0
Equestrianism,34.161290,71.120000,176.823939,7.848306e+11,5.644934e+07,0
Fencing,26.709931,75.787747,181.153883,7.228595e+11,1.094885e+08,0
Football,22.925226,73.167088,177.954452,5.021586e+11,5.165784e+07,0
Golf,31.859649,78.980392,179.017544,1.511587e+12,1.551052e+08,0
Gymnastics,23.630015,63.000384,167.417239,9.874812e+11,1.039428e+08,0
Handball,26.550826,88.700984,188.272608,5.494235e+11,5.129023e+07,0
Hockey,25.698759,73.125594,176.661222,3.941901e+11,1.329644e+08,0
Judo,25.405752,82.768914,177.229476,4.041821e+11,6.135140e+07,0
Modern Pentathlon,26.090909,72.507299,179.910747,6.310685e+11,5.986274e+07,0
Rowing,25.347101,84.137140,187.344350,6.680799e+11,6.522044e+07,0
Rugby Sevens,26.099099,90.540541,182.639640,1.537157e+12,6.828972e+07,0
Sailing,29.584063,78.761579,180.424715,5.081570e+11,5.904374e+07,0
Shooting,33.114028,78.094247,176.126230,5.218063e+11,9.086429e+07,0
Swimming,21.592779,77.724973,184.254633,6.663243e+11,7.829380e+07,0
Table Tennis,27.356250,71.835017,177.225589,9.620083e+11,1.520270e+08,0
Taekwondo,24.889362,74.247863,181.521368,5.479307e+11,5.815662e+07,0
Tennis,26.022695,78.839311,184.826648,7.808304e+11,9.454968e+07,0
Trampolining,24.983607,65.898305,171.262295,1.652489e+12,7.485038e+07,0
Triathlon,27.868526,68.744000,180.143426,1.206062e+12,7.560345e+07,0
Volleyball,25.492135,86.446858,193.010819,7.385544e+11,6.998074e+07,0
Water Polo,25.789241,87.105851,186.749344,5.910419e+11,6.555774e+07,0
Weightlifting,25.438580,81.479975,169.233964,4.046709e+11,6.374815e+07,0
Wrestling,25.635622,76.443509,172.930432,4.424550e+11,7.248827e+07,0

In [10]:
final=medal_winner_grouped.append(no_medal_winner_grouped)
final['sport']=final.index

In [11]:
final.loc['Archery']

,Age,Weight,Height,GDP,Population,Won,sport
Sport,,,,,,,
Archery,25.306122,78.588542,178.989583,1.565370e+12,1.617803e+08,1,Archery
Archery,27.469014,76.708006,178.261654,7.817921e+11,1.355641e+08,0,Archery